### ISSUE TITLE
L'affiche est designée

### ISSUE THREAD

**Issue by liZe** [AFPy/pyconfr_2018#33]
On vise le 31 août pour arrêter le design de l'affiche et le 15 septembre pour avoir la version finale avec les logos des entreprises.

**Comment by annabellou** [comment]
Voici l'affiche, format A3, en couleurs CMJN et avec des fonds perdus de 5mm sur chaque côté. Enjoy ;)

[Affiche Pycon 2018 CMJN fonds perdus.pdf](https://github.com/AFPy/pyconfr_2018/files/2383369/Affiche.Pycon.2018.CMJN.fonds.perdus.pdf)

**Comment by annabellou** [comment]
Ajout du logo de l'IMT

[Affiche Pycon 2018 CMJN fonds perdus - V2.pdf](https://github.com/AFPy/pyconfr_2018/files/2383673/Affiche.Pycon.2018.CMJN.fonds.perdus.-.V2.pdf)
