### ISSUE TITLE
Regénérer un thème pelican

### ISSUE THREAD

**Issue by jbbqqf** [AFPy/pyconfr_2018#4]
La prochaine pyconfr sera organisée à Lille ! Et la couleur dominante de Lille est le rouge ! (Avec du noir en mineur)

Je suis en train d'essayer d'intégrer ces couleurs dans le site à la place du bleu / jaune pour faire une nouvelle proposition. J'imagine qu'elles ont été choisies car elles sont proches du logo de python.

Cela dit, ce serait vraiment cool qu'on puisse utiliser ce #E2001A dans la charte :D 

Bref, j'aimerais tester avant de pusher, mais je n'arrive pas à regénérer le thème, et plus particulièrement la css. N'étant pas familier des outils utilisés je n'arrive pas à faire une recherche efficace en ligne.

Quelqu'un saurait-il m'aider ?

PS:
![python_logo_with_lille_colors](https://user-images.githubusercontent.com/8479617/36998408-1f562dd6-20bd-11e8-9285-9bc727696123.png)

![python_logo_with_lille_colors_grey](https://user-images.githubusercontent.com/8479617/36998416-27560ff6-20bd-11e8-8d5e-c6eb221f16fa.png)

:smiley: :smiley: :smiley:

**Comment by arthru** [comment]
Il y a une graphiste de Kozea qui travaille sur un logo. Du choix du logo découleront les couleurs finales du site... Il y a des personnes de Kozea et Hashbang qui feront l'intégration web.
Je fait un point avec tout ce monde là mardi soir.

Il me semble que les couleurs actuelles sont celles du département. @LucienD c'est bien ça ?

Par contre, pour la génération du site, les instructions contenues dans le README sont à jour...

**Comment by jbbqqf** [comment]
Je me permets d'insister sur ce rouge. Je t'invite à confirmer avec les collègues lillois de l'orga, mais il manquera quelque chose à cette charte si elle ne le contient pas. Ce serait comme faire une charte graphique pour la ville de Toulouse sans rose. ;)

En ce qui concerne la regénération du site, peux-tu m'indiquer précisément quelle commande regénère les templates du thème ?

**Comment by arthru** [comment]
Je me déclare incompétent en choix de couleurs. On a laissé carte blanche aux graphistes pour ces choix. J'ai peur que ce soit un peu tard pour donner des instructions sur ce travail...

Quoi qu'il en soit, je les voit mardi soir, je te dirais ce qu'il en est...
