### ISSUE TITLE
Archivage

### ISSUE THREAD

**Issue by Seluj78** [AFPy/pyconfr_2018#57]
cc @liZe, @debnet et @JulienPalard: Pensez vous que nous allons modifier ce site ou on peux archiver le repo ?

**Comment by JulienPalard** [comment]
Il n'est pas migré sur ansible, donc j'exclus pas qu'y'ai une mini retouche a y faire a un moment, et je ne voit pas *trop* l'intérêt de l'archiver tant qu'il est en ligne.

**Comment by Seluj78** [comment]
okay ! 👌
